FROM python:3.9.7-slim-bullseye

WORKDIR /usr/src/app

RUN apt-get update

RUN apt install -y gcc libpq-dev

RUN pip install --no-cache psycopg2

RUN pip install --no-cache mlflow==2.7.1

CMD mlflow server --backend-store-uri $BACKEND_STORE_URI --host $HOST --artifacts-destination $ARTIFACTS_DESTINATION --workers 20 --gunicorn-opts '--timeout 600'